# Generated by Django 4.2.4 on 2023-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCOUNT_SID', models.CharField(blank=True, max_length=200)),
                ('AUTH_TOKEN', models.CharField(blank=True, max_length=200)),
                ('VARIFY_SID', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
