# Generated by Django 4.2.4 on 2023-10-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantid', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
            ],
        ),
    ]
