# Generated by Django 4.2.4 on 2023-09-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0006_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
