# Generated by Django 4.2.4 on 2023-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0007_alter_gallery_description_alter_gallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
