# Generated by Django 4.2.4 on 2023-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0008_alter_horoscope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=10)),
                ('createdOntarget', models.CharField(blank=True, max_length=130)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
