# Generated by Django 4.2.4 on 2023-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_due',
            field=models.IntegerField(),
        ),
    ]
