# Generated by Django 4.2.4 on 2023-09-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0012_profile_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='payment')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
