# Generated by Django 4.2.4 on 2023-10-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0013_paymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInitiate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('source', models.CharField(max_length=150)),
                ('transaction_id', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
    ]
